[workspace]
members = [
    "parsely_lexer",
    "parsely_parser",
    "parsely_diagnostics",
    "parsely_macros",
    "parsely_gen_ts",
    "parsely_analysis",
    "parsely",
    "parsely_lsp/lsp_server",
]
resolver = "2"
