[package]
name = "parsely-gen-ts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsely-lexer = { path = "../parsely_lexer" }
parsely-parser = { path = "../parsely_parser" }
colored = "2.0.0"